# Generated by Django 4.2.3 on 2023-08-12 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=64)),
                ('año_estreno', models.IntegerField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PeliCreador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
