# Generated by Django 4.2.3 on 2023-08-09 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.CharField(max_length=64)),
                ('nota', models.IntegerField()),
                ('detalle', models.CharField(max_length=256)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CursosCreados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
