# Generated by Django 4.2.3 on 2023-07-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.CharField(max_length=64)),
                ('nota', models.IntegerField()),
                ('detalle', models.CharField(max_length=256)),
            ],
        ),
    ]
