# Generated by Django 4.2.3 on 2023-08-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opiniones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='subtitulo',
            new_name='mini_opinion',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='pelicula',
            field=models.CharField(max_length=32),
        ),
    ]
